# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jay Lin
tagline:          'Jay&apos;s Blog'
description:      'Solve real world problems by leveraging the latest and greatest Microsoft technologies (.NET Core, Azure).'
url:              http://jaycoder.net
baseUrl:          /

author:
  name:           'Jay Lin'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jay-coder

google:
  tag_manager:
    container_id: GTM-5FDRV8L

plugins: [jekyll-paginate, jekyll-gist]