# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jay Coder
tagline:          'Jay&apos;s Blog'
description:      'Solve real world problems by leveraging the latest and greatest Microsoft technologies (.NET Core, Azure).'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jay Lin'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jay-coder

plugins: [jekyll-paginate, jekyll-gist]